require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods',
  :deterministic_uuids => false

# Needed for Firebase Swift pods when CocoaPods is building pods as static libraries.
# See: "Swift pods cannot yet be integrated as static libraries" error.
use_modular_headers!

prepare_react_native_project!

target 'ExpoFirebaseSkeleton' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # Fix for gRPC-C++ module map not found error
    # The gRPC-Core module map is located in "Target Support Files" but referenced in "Headers/Private"
    # This affects gRPC-C++ and FirebaseFirestoreInternal among others.
    # We update all xcconfig files in Target Support Files to ensure any target referencing the wrong path is fixed.
    target_support_files = File.join(installer.sandbox.root, 'Target Support Files')
    Dir.glob("#{target_support_files}/**/*.xcconfig").each do |xcconfig|
      if File.exist?(xcconfig)
        content = File.read(xcconfig)
        if content.include? 'Headers/Private/grpc/gRPC-Core.modulemap'
          new_content = content.gsub(
            '${PODS_ROOT}/Headers/Private/grpc/gRPC-Core.modulemap',
            '${PODS_ROOT}/Target Support Files/gRPC-Core/gRPC-Core.modulemap'
          )
          File.write(xcconfig, new_content)
        end
      end
    end

    # Fix for Firebase *-Swift.h not found error
    # Firebase.h tries to import Swift headers but they are sometimes not found in the search paths.
    # We patch Firebase.h to use a safer include check for all Swift header imports.
    firebase_header = File.join(installer.sandbox.root, 'Headers/Private/Firebase/Firebase.h')
    if File.exist?(firebase_header)
      File.chmod(0644, firebase_header)
      content = File.read(firebase_header)
      
      # Regex to match #import <Module/Module-Swift.h>
      regex = /#import <(\w+)\/(\w+-Swift\.h)>/
      
      new_content = content.gsub(regex) do |match|
        module_name = $1
        header_name = $2
        "#if __has_include(<#{module_name}/#{header_name}>)\n" +
        "  #import <#{module_name}/#{header_name}>\n" +
        "#elif __has_include(\"#{header_name}\")\n" +
        "  #import \"#{header_name}\"\n" +
        "#endif"
      end
      
      File.write(firebase_header, new_content)
    end
  end
end
